In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import time

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE

In [3]:
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)
    selectk_features=fit1.transform(indep_x)
    return selectk_features

In [4]:
def split_scalar(indep_x, dep_y):
    x_train, x_test, y_train, y_test = train_test_split(indep_x, dep_y, test_size=0.25, random_state=0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test)
    return x_train, x_test, y_train, y_test

In [5]:
def rscore_prediction(regressor,x_test):
    y_pred=regressor.predict(x_test)
    from sklearn.metrics import r2_score
    r_score=r2_score(y_test,y_pred)
    return r_score

In [6]:
def linear(x_train, y_train, x_test):
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(x_train, y_train)
    r_score = regressor.score(x_test, y_test)
    return r_score, x_test, y_test

In [7]:
def svml(x_train, y_train, x_test):
    from sklearn.svm import SVR
    regressor = SVR(kernel='linear')
    regressor.fit(x_train, y_train)
    r_score = rscore_prediction(regressor, x_test)
    return r_score, x_test, y_test

In [8]:
def Decision (x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor=DecisionTreeRegressor(criterion='friedman_mse',random_state=0)
    regressor.fit(x_train,y_train)
    r_score=rscore_prediction(regressor,x_test)
    return r_score,x_test,y_test

In [9]:
def random(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor=RandomForestRegressor(n_estimators=10,criterion='friedman_mse',random_state=0)
    regressor.fit(x_train,y_train)
    r_score=rscore_prediction(regressor,x_test)
    return r_score,x_test,y_test

In [20]:
def selectk_regression(rscorelin, rscoresvml, rscoredes, rscorerf):
    columns = ['linear', 'svml', 'Decision', 'random']
    dataframe = pd.DataFrame(columns=columns)
    dataframe.loc['chisquare'] = [rscorelin[0], rscoresvml[0], rscoredes[0], rscorerf[0]]
    return dataframe

In [21]:
dataset1=pd.read_csv("car details.csv",index_col=None)
df2=dataset1
df2

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [22]:
df2=pd.get_dummies(df2,drop_first=True)
indep_x=df2.drop('Price',1)
dep_y=df2['Price']
df2.tail(5)
df2

,Price,Year,Kilometer,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Make_BMW,Make_Chevrolet,...,Max Torque_95 Nm @ 4000 rpm,Max Torque_96 Nm @ 3000 rpm,Max Torque_96 Nm @ 3500 rpm,Max Torque_98 Nm @ 3000 rpm,Max Torque_99 Nm @ 4500 rpm,Max Torque_99.08 Nm @ 4500 rpm,Max Torque_99.081 Nm @ 4500 rpm,Max Torque_99@2800,Drivetrain_FWD,Drivetrain_RWD
0,505000,2017,87150,3990.0,1680.0,1505.0,5.0,35.0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,450000,2014,75000,3995.0,1695.0,1555.0,5.0,42.0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,220000,2011,67000,3585.0,1595.0,1550.0,5.0,35.0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,799000,2019,37500,3995.0,1745.0,1510.0,5.0,37.0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,1950000,2018,69000,4735.0,1830.0,1795.0,7.0,55.0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,850000,2016,90300,4585.0,1890.0,1785.0,7.0,70.0,0,0,...,0,0,0,0,0,0,0,0,1,0
2055,275000,2014,83000,3495.0,1550.0,1500.0,5.0,32.0,0,0,...,0,0,0,0,0,0,0,0,1,0
2056,240000,2013,73000,3795.0,1680.0,1427.0,5.0,45.0,0,0,...,0,0,0,0,0,0,0,0,1,0
2057,4290000,2018,60474,4936.0,1868.0,1479.0,5.0,65.0,1,0,...,0,0,0,0,0,0,0,0,0,1
2058,670000,2017,72000,3995.0,1745.0,1880.0,7.0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1

In [23]:
import numpy as np

# Check for NaN values in indep_x and dep_y
nan_indices = np.isnan(indep_x).any(axis=1) | np.isnan(dep_y)

# Remove rows with NaN values from both indep_x and dep_y
indep_x = indep_x[~nan_indices]
dep_y = dep_y[~nan_indices]

In [24]:
df2.isnull().sum()

Price                               0
Year                                0
Kilometer                           0
Length                             64
Width                              64
                                   ..
Max Torque_99.08 Nm @ 4500 rpm      0
Max Torque_99.081 Nm @ 4500 rpm     0
Max Torque_99@2800                  0
Drivetrain_FWD                      0
Drivetrain_RWD                      0
Length: 1929, dtype: int64

In [25]:
df2.fillna(0, axis=1, inplace=True)

In [26]:
df2.isnull().sum()

Price                              0
Year                               0
Kilometer                          0
Length                             0
Width                              0
                                  ..
Max Torque_99.08 Nm @ 4500 rpm     0
Max Torque_99.081 Nm @ 4500 rpm    0
Max Torque_99@2800                 0
Drivetrain_FWD                     0
Drivetrain_RWD                     0
Length: 1929, dtype: int64

In [30]:
kbest =selectkbest(indep_x,dep_y,6)
rscorelin=[]
rscoresvml=[]
rscoredes=[]
rscorerf=[]

In [31]:
x_train, x_test, y_train, y_test = split_scalar(kbest, dep_y)
r_score,x_test,y_test= linear(x_train, y_train, x_test)
rscorelin.append(r_score)
r_score, x_test, y_test= svml(x_train, y_train, x_test)
rscoresvml.append(r_score)
r_score, x_test, y_test= Decision(x_train, y_train, x_test)
rscoredes.append(r_score)
rscore,x_test, y_test = random(x_train, y_train, x_test)
rscorerf.append(r_score)
result= selectk_regression (rscorelin,rscoresvml,rscoredes,rscorerf)

In [29]:
#4 result

             linear      svml  Decision    random
chisquare  0.182604 -0.129481  0.577208  0.577208

In [32]:
#6 result

             linear      svml  Decision    random
chisquare  0.211442 -0.129228  0.597373  0.597373